### ISSUE TITLE
[Q][Support] Khi chạy "node app.js" bị báo lỗi "Error: Cannot find module 'express'"

### ISSUE THREAD

**Issue by vuhung** [Openroadvietnam/openaccounting#13]
# Em new với nodejs nhé.

Em cài thử 

  495  git clone https://github.com/Openroadvietnam/openaccounting.git
  497  cd openaccounting/
  499  node app.js 

-> bị báo thiếu/lỗi

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vuhung/tmp/openaccounting/app.js:16:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

  502  npm install express
  504  npm install body-parser
  506  npm install passport
  508  npm install phantom
  510  npm install mongoose
-> Cài xong 1 loạt và chạy thử lại "node app.js" vẫn bị báo thiếu gói.

Có lẽ nodejs chưa cài đặt, cấu hình đúng hay sao?
Mong các bác giúp đỡ

vuhung@d330:~/tmp/openaccounting$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
vuhung@d330:~/tmp/openaccounting$ uname -a
Linux d330 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by letrunghieu** [comment]
Sau lệnh `cd openaccounting/`, anh chạy thêm `npm install` nữa để nó tự cài hết dependencies rồi mới chạy tiếp `node app.js` anh ạ.

**Comment by dominhhai** [comment]
Lần đầu sau khi pull project về, anh chạy lệnh `npm install` tại thư mục project trước để cài các gói phụ thuộc vào local project, rồi mới chạy chương trình.

**Comment by vuhung** [comment]
Cảm ơn 2 bác. Em chạy thử và lỗi như sau:

```
vuhung@d330:~/tmp/openaccounting$ npm install
```

```
vuhung@d330:~/tmp/openaccounting$ node app.js 

module.js:340
    throw err;
    ^
Error: Cannot find module 'iconv-lite'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vuhung/tmp/openaccounting/node_modules/nodemailer/node_modules/libmime/src/charset.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Warning khi chạy "npm install"

```
vuhung@d330:~/tmp/openaccounting$ npm install 
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/excel-report requires node-zip@'latest' but will load
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/node-zip,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/excel-report requires elementtree@'latest' but will load
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/elementtree,
npm WARN unmet dependency which is version 0.1.6
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/excel-report requires underscore@'latest' but will load
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/underscore,
npm WARN unmet dependency which is version 1.8.2
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/jshint/node_modules/htmlparser2/node_modules/domutils/node_modules/dom-serializer requires domelementtype@'~1.1.1' but will load
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/jshint/node_modules/htmlparser2/node_modules/domelementtype,
npm WARN unmet dependency which is version 1.3.0
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/jshint/node_modules/htmlparser2/node_modules/domutils/node_modules/dom-serializer requires entities@'~1.1.1' but will load
npm WARN unmet dependency /home/vuhung/tmp/openaccounting/node_modules/jshint/node_modules/htmlparser2/node_modules/entities,
npm WARN unmet dependency which is version 1.0.0
```

**Comment by dominhhai** [comment]
anh thử vào thư mục `openaccounting/node_modules/nodemailer/node_modules/libmime/node_modules` xem có cái thư mục nào là `iconv-lite` không ạ? Nếu không có thì anh tự cài vào xem sao.

`cd openaccounting/node_modules/nodemailer/node_modules/libmime/node_modules`
`npm install iconv-lite` hoặc `npm install`

Chỗ warning khi chạy `npm install` kia không liên quan tới việc bị thiếu module `iconv-lite` thì phải.

**Comment by vuhung** [comment]
@dominhhai 

Mình chạy lại và lỗi như sau:

```
vuhung@d330:~/tmp/openaccounting$ npm install
vuhung@d330:~/tmp/openaccounting$ !559
cd node_modules/nodemailer/node_modules/libmime/node_modules
bash: cd: node_modules/nodemailer/node_modules/libmime/node_modules: No such file or directory

  560  npm install iconv-lite
  562  npm install addressparser
  564  npm install through2
  566  npm install duplexer2
  568  npm install xlsx
  570  npm install lodash.defaults
  574  npm install lodash.map

vuhung@d330:~/tmp/openaccounting$ node app.js 

module.js:340
    throw err;
    ^
Error: Cannot find module 'zlibjs/bin/rawdeflate.min'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vuhung/tmp/openaccounting/node_modules/node-zip/node_modules/jszip/lib/flate.js:4:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by dominhhai** [comment]
em cũng không hiểu sao trên máy anh lại không install được sub-dependences nữa.
em vừa thử cài lại thì vẫn bình thường.

**Comment by vuhung** [comment]
Mình dùng trên Ubuntu 14.04
Node js mặc định cài từ apt-get.
